'use client';

import { useEffect, useRef, useState, type ChangeEvent } from 'react';
import { CheckCircle2, FileText, Upload } from 'lucide-react';
import { PageShell } from '@/components/layout/page-shell';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { apiClient } from '@/lib/api-client';

interface BookkeepingEntry {
  date: string;
  party: string;
  type: 'credit' | 'debit';
  amount: number;
  category?: string;
  gst_amount?: number;
  running_balance?: number;
  confidence?: number;
}

interface BalanceSummary {
  total_credits: number;
  total_debits: number;
  net_cash_flow: number;
  total_gst_paid: number;
  total_itc_claimable: number;
  transaction_count: number;
  category_counts?: Record<string, number>;
  insights?: string[];
  action_items?: Array<{ message: string }>;
}

interface StatementUploadHistoryItem {
  upload_id?: string;
  file_name?: string;
  count?: number;
  parsed?: boolean;
  message?: string;
  created_at?: string;
}

interface InvoiceUploadHistoryItem {
  invoice_id?: string;
  file_name?: string;
  party?: string;
  amount?: number;
  date?: string;
  created_at?: string;
}

interface BookkeepingSummary {
  entries: BookkeepingEntry[];
  balance_summary: BalanceSummary;
  recommendations: string[];
  statement_uploads?: StatementUploadHistoryItem[];
  invoice_uploads?: InvoiceUploadHistoryItem[];
}

interface StatementUploadResult {
  uploaded: boolean;
  parsed?: boolean;
  count: number;
  parsed_count?: number;
  inserted_count?: number;
  duplicate_count?: number;
  failed_count?: number;
  already_existing?: boolean;
  message?: string;
  transactions: Array<{ id?: string; party?: string; amount?: number; type?: string; date?: string; category?: string }>;
}

interface InvoiceUploadResult {
  uploaded: boolean;
  invoice?: {
    invoice_id?: string;
    party?: string;
    amount?: number;
    date?: string;
    extracted?: Record<string, any>;
  };
  linked_transaction?: {
    id?: string;
    category?: string;
    sub_category?: string;
    confidence?: number;
  } | null;
  deadline?: {
    due_date?: string;
    meta?: Record<string, any>;
  };
  reminders_queued?: number;
}

interface FinancialReportResult {
  status: 'ok' | 'error';
  message?: string;
  user_id?: string;
  transactions_count?: number;
  gross_income?: number;
  total_deductions?: number;
  taxable_income?: number;
  tds_paid?: number;
}

export default function BookkeepingPage() {
  const statementInputRef = useRef<HTMLInputElement>(null);
  const invoiceInputRef = useRef<HTMLInputElement>(null);
  const apiBaseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

  const [isStatementUploading, setIsStatementUploading] = useState(false);
  const [isInvoiceUploading, setIsInvoiceUploading] = useState(false);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);
  const [statusType, setStatusType] = useState<'success' | 'error' | null>(null);
  const [summary, setSummary] = useState<BookkeepingSummary | null>(null);
  const [isSummaryLoading, setIsSummaryLoading] = useState(true);
  const [latestStatementResult, setLatestStatementResult] = useState<StatementUploadResult | null>(null);
  const [latestInvoiceResult, setLatestInvoiceResult] = useState<InvoiceUploadResult | null>(null);
  const [financialReport, setFinancialReport] = useState<FinancialReportResult | null>(null);
  const [isFinancialReportGenerating, setIsFinancialReportGenerating] = useState(false);
  const [isFinancialReportDownloading, setIsFinancialReportDownloading] = useState(false);
  const [lastAutoGeneratedCount, setLastAutoGeneratedCount] = useState<number>(-1);

  const userId = 'default';

  const setStatus = (message: string, type: 'success' | 'error') => {
    setStatusMessage(message);
    setStatusType(type);
  };

  const getErrorMessage = (error: unknown, fallback: string) => {
    const maybeAxios = error as {
      response?: {
        data?: {
          detail?: string;
        };
      };
      message?: string;
    };
    return maybeAxios?.response?.data?.detail || maybeAxios?.message || fallback;
  };

  const unwrapApiData = <T,>(response: any): T => {
    const payload = response?.data ?? response;
    return (payload?.data ?? payload) as T;
  };

  const generateFinancialReport = async (silent = false, transactionCountHint?: number) => {
    try {
      if (!silent) {
        setIsFinancialReportGenerating(true);
      }
      const response = await apiClient.generateFinancialReport(userId);
      const data = unwrapApiData<FinancialReportResult>(response);
      setFinancialReport(data);

      if (data?.status === 'ok') {
        if (typeof transactionCountHint === 'number') {
          setLastAutoGeneratedCount(transactionCountHint);
        }
        if (!silent) {
          setStatus(`Financial report prepared (${data.transactions_count ?? 0} transactions)`, 'success');
        }
      } else if (!silent) {
        setStatus(data?.message || 'Financial report generation failed', 'error');
      }
    } catch (error) {
      if (!silent) {
        setStatus(getErrorMessage(error, 'Financial report generation failed'), 'error');
      }
    } finally {
      if (!silent) {
        setIsFinancialReportGenerating(false);
      }
    }
  };

  const downloadFinancialReport = async () => {
    try {
      setIsFinancialReportDownloading(true);
      const link = document.createElement('a');
      link.href = `${apiBaseUrl}/reports/financial/download/${encodeURIComponent(userId)}?format=html`;
      link.download = `Financial-Report-${userId}.html`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      setStatus('Financial report downloaded.', 'success');
    } catch (error) {
      setStatus(getErrorMessage(error, 'Financial report download failed'), 'error');
    } finally {
      setIsFinancialReportDownloading(false);
    }
  };

  const loadLedgerSummary = async () => {
    try {
      setIsSummaryLoading(true);
      const response = await apiClient.getBookkeepingLedger(userId);
      const data = unwrapApiData<BookkeepingSummary>(response);
      if (data && typeof data === 'object') {
        setSummary(data);
        const txCount = Number(data?.balance_summary?.transaction_count ?? 0);
        if (txCount > 0 && txCount !== lastAutoGeneratedCount) {
          void generateFinancialReport(true, txCount);
        }
      }
    } catch (error) {
      setStatus(getErrorMessage(error, 'Unable to load bookkeeping summary'), 'error');
    } finally {
      setIsSummaryLoading(false);
    }
  };

  useEffect(() => {
    loadLedgerSummary();
  }, []);

  const triggerStatementPicker = () => {
    statementInputRef.current?.click();
  };

  const triggerInvoicePicker = () => {
    invoiceInputRef.current?.click();
  };

  const handleStatementFileChange = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    try {
      setIsStatementUploading(true);
      const response = await apiClient.uploadBookkeepingStatement(file, userId);
      const parsed = unwrapApiData<StatementUploadResult>(response);
      if (parsed) {
        setLatestStatementResult(parsed);
      }
      await loadLedgerSummary();
      const insertedCount = parsed?.inserted_count ?? parsed?.count ?? 0;
      const duplicateCount = parsed?.duplicate_count ?? 0;

      if (insertedCount > 0) {
        await generateFinancialReport(true, insertedCount);
      }

      if (duplicateCount > 0 && insertedCount === 0) {
        const duplicateMessage = parsed?.message || `All transactions from ${file.name} are already existing in ledger.`;
        setStatus(duplicateMessage, 'error');
        window.alert(duplicateMessage);
      } else if (insertedCount > 0) {
        const suffix = duplicateCount > 0 ? ` • ${duplicateCount} already existing skipped` : '';
        setStatus(`Statement uploaded: ${file.name} • ${insertedCount} new transactions added${suffix}`, 'success');
      } else {
        setStatus(parsed?.message || 'Statement uploaded, but no transactions were parsed.', 'error');
      }
    } catch (error) {
      const message = getErrorMessage(error, 'Statement upload failed');
      setStatus(message, 'error');
    } finally {
      setIsStatementUploading(false);
      event.target.value = '';
    }
  };

  const handleInvoiceFileChange = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    try {
      setIsInvoiceUploading(true);
      const response = await apiClient.uploadBookkeepingInvoice(file, userId);
      const parsed = unwrapApiData<InvoiceUploadResult>(response);
      if (parsed) {
        setLatestInvoiceResult(parsed);
      }
      await loadLedgerSummary();
      const fyEnd = parsed?.deadline?.meta?.financial_year_end;
      const queued = Number(parsed?.reminders_queued ?? 0);
      const suffix = fyEnd ? ` • Deadline set for FY end ${fyEnd}` : '';
      setStatus(`Invoice uploaded: ${file.name} and parsed successfully${suffix}. Reminders queued: ${queued}`, 'success');
    } catch (error) {
      const message = getErrorMessage(error, 'Invoice upload failed');
      setStatus(message, 'error');
    } finally {
      setIsInvoiceUploading(false);
      event.target.value = '';
    }
  };

  const statementUploads = summary?.statement_uploads ?? [];
  const invoiceUploads = summary?.invoice_uploads ?? [];

  return (
    <PageShell
      title="Ledger"
      subtitle="Manage transactions, statements, and invoices"
      headerAction={
        <div style={{ display: 'flex', gap: '1rem' }}>
          <Button
            variant="primary"
            onClick={triggerStatementPicker}
            disabled={isStatementUploading}
          >
            {isStatementUploading ? 'Uploading Statement...' : (
              <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.45rem' }}>
                <Upload size={16} />
                <span>Upload Statement</span>
              </span>
            )}
          </Button>
          <Button
            variant="secondary"
            onClick={triggerInvoicePicker}
            disabled={isInvoiceUploading}
          >
            {isInvoiceUploading ? 'Uploading Invoice...' : (
              <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.45rem' }}>
                <FileText size={16} />
                <span>Upload Invoice</span>
              </span>
            )}
          </Button>
        </div>
      }
    >
      <input
        ref={statementInputRef}
        type="file"
        accept=".pdf,.csv,.xlsx,.xls"
        onChange={handleStatementFileChange}
        style={{ display: 'none' }}
      />
      <input
        ref={invoiceInputRef}
        type="file"
        accept=".pdf,.png,.jpg,.jpeg"
        onChange={handleInvoiceFileChange}
        style={{ display: 'none' }}
      />

      {statusMessage && statusType && (
        <div
          style={{
            marginBottom: '1rem',
            padding: '0.75rem 1rem',
            borderRadius: '0.5rem',
            border: `1px solid ${statusType === 'success' ? 'var(--emerald)' : 'var(--rose)'}`,
            color: statusType === 'success' ? 'var(--emerald)' : 'var(--rose)',
            background: statusType === 'success' ? 'var(--card-glow-emerald)' : 'rgba(244, 63, 94, 0.08)',
          }}
        >
          {statusMessage}
        </div>
      )}

      <div style={{ marginBottom: '1rem' }}>
        <Card title="Transaction Summary" subtitle="Auto-generated from parsed statements and invoices">
          {isSummaryLoading ? (
            <p style={{ margin: 0, color: 'var(--muted)' }}>Loading summary...</p>
          ) : !summary?.balance_summary ? (
            <p style={{ margin: 0, color: 'var(--muted)' }}>Upload a statement or invoice to generate summary.</p>
          ) : (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))', gap: '0.75rem' }}>
              <div style={{ background: 'var(--bg3)', borderRadius: '0.5rem', padding: '0.75rem' }}>
                <div style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>Credits</div>
                <div style={{ fontWeight: 700 }}>₹{summary.balance_summary.total_credits.toFixed(2)}</div>
              </div>
              <div style={{ background: 'var(--bg3)', borderRadius: '0.5rem', padding: '0.75rem' }}>
                <div style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>Debits</div>
                <div style={{ fontWeight: 700 }}>₹{summary.balance_summary.total_debits.toFixed(2)}</div>
              </div>
              <div style={{ background: 'var(--bg3)', borderRadius: '0.5rem', padding: '0.75rem' }}>
                <div style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>Net Cash Flow</div>
                <div style={{ fontWeight: 700 }}>₹{summary.balance_summary.net_cash_flow.toFixed(2)}</div>
              </div>
              <div style={{ background: 'var(--bg3)', borderRadius: '0.5rem', padding: '0.75rem' }}>
                <div style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>GST Paid</div>
                <div style={{ fontWeight: 700 }}>₹{summary.balance_summary.total_gst_paid.toFixed(2)}</div>
              </div>
              <div style={{ background: 'var(--bg3)', borderRadius: '0.5rem', padding: '0.75rem' }}>
                <div style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>ITC Claimable</div>
                <div style={{ fontWeight: 700 }}>₹{summary.balance_summary.total_itc_claimable.toFixed(2)}</div>
              </div>
              <div style={{ background: 'var(--bg3)', borderRadius: '0.5rem', padding: '0.75rem' }}>
                <div style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>Transactions</div>
                <div style={{ fontWeight: 700 }}>{summary.balance_summary.transaction_count}</div>
              </div>
            </div>
          )}
        </Card>
      </div>

      <div style={{ marginBottom: '1rem' }}>
        <Card title="Financial Report" subtitle="Backend-generated report from bookkeeping transactions">
          <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap', marginBottom: '0.9rem' }}>
            <Button
              variant="primary"
              onClick={() => void generateFinancialReport(false)}
              disabled={isFinancialReportGenerating || isSummaryLoading}
            >
              {isFinancialReportGenerating ? 'Generating Financial Report...' : 'Generate Financial Report'}
            </Button>
            <Button
              variant="secondary"
              onClick={() => void downloadFinancialReport()}
              disabled={isFinancialReportDownloading}
            >
              {isFinancialReportDownloading ? 'Downloading...' : 'Download Financial Report'}
            </Button>
          </div>

          {!financialReport ? (
            <p style={{ margin: 0, color: 'var(--muted)' }}>
              Upload a statement to auto-prepare the financial report.
            </p>
          ) : financialReport.status !== 'ok' ? (
            <p style={{ margin: 0, color: 'var(--rose)' }}>{financialReport.message || 'Financial report is not ready yet.'}</p>
          ) : (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))', gap: '0.75rem' }}>
              <div style={{ background: 'var(--bg3)', borderRadius: '0.5rem', padding: '0.75rem' }}>
                <div style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>Transactions</div>
                <div style={{ fontWeight: 700 }}>{financialReport.transactions_count ?? 0}</div>
              </div>
              <div style={{ background: 'var(--bg3)', borderRadius: '0.5rem', padding: '0.75rem' }}>
                <div style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>Gross Income</div>
                <div style={{ fontWeight: 700 }}>₹{Number(financialReport.gross_income ?? 0).toFixed(2)}</div>
              </div>
              <div style={{ background: 'var(--bg3)', borderRadius: '0.5rem', padding: '0.75rem' }}>
                <div style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>Total Deductions</div>
                <div style={{ fontWeight: 700 }}>₹{Number(financialReport.total_deductions ?? 0).toFixed(2)}</div>
              </div>
              <div style={{ background: 'var(--bg3)', borderRadius: '0.5rem', padding: '0.75rem' }}>
                <div style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>Taxable Income</div>
                <div style={{ fontWeight: 700 }}>₹{Number(financialReport.taxable_income ?? 0).toFixed(2)}</div>
              </div>
            </div>
          )}
        </Card>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>
        <Card title="Recent Statements" subtitle="Bank statements and records">
          <div style={{ padding: '2rem', textAlign: 'center', color: 'var(--muted)' }}>
            {statementUploads.length === 0 ? (
              <p>No statements uploaded yet</p>
            ) : (
              <div style={{ textAlign: 'left' }}>
                {statementUploads.map((item, index) => {
                  const createdAtText = item.created_at
                    ? new Date(item.created_at).toLocaleDateString('en-IN')
                    : null;
                  const countText = typeof item.count === 'number' ? ` (${item.count} txn)` : '';
                  return (
                    <p
                      key={item.upload_id || `${item.file_name || 'statement'}-${item.created_at || index}`}
                      style={{ margin: '0.25rem 0', color: 'var(--text)' }}
                    >
                      • {item.file_name || `Statement ${index + 1}`}{countText}{createdAtText ? ` • ${createdAtText}` : ''}
                    </p>
                  );
                })}
              </div>
            )}
            {statementUploads.length === 0 && (
              <Button
                variant="primary"
                style={{ marginTop: '1rem' }}
                onClick={triggerStatementPicker}
                disabled={isStatementUploading}
              >
                {isStatementUploading ? 'Uploading...' : 'Upload First Statement'}
              </Button>
            )}
          </div>
        </Card>

        <Card title="Invoices" subtitle="Uploaded invoices and documents">
          <div style={{ padding: '2rem', textAlign: 'center', color: 'var(--muted)' }}>
            {invoiceUploads.length === 0 ? (
              <p>No invoices uploaded yet</p>
            ) : (
              <div style={{ textAlign: 'left' }}>
                {invoiceUploads.map((item, index) => {
                  const createdAtText = item.created_at
                    ? new Date(item.created_at).toLocaleDateString('en-IN')
                    : null;
                  const amountText = typeof item.amount === 'number' ? ` • ₹${item.amount.toFixed(2)}` : '';
                  const partyText = item.party ? ` • ${item.party}` : '';
                  return (
                    <p
                      key={item.invoice_id || `${item.file_name || 'invoice'}-${item.created_at || index}`}
                      style={{ margin: '0.25rem 0', color: 'var(--text)' }}
                    >
                      • {item.file_name || `Invoice ${index + 1}`}{partyText}{amountText}{createdAtText ? ` • ${createdAtText}` : ''}
                    </p>
                  );
                })}
              </div>
            )}
            {invoiceUploads.length === 0 && (
              <Button
                variant="primary"
                style={{ marginTop: '1rem' }}
                onClick={triggerInvoicePicker}
                disabled={isInvoiceUploading}
              >
                {isInvoiceUploading ? 'Uploading...' : 'Upload First Invoice'}
              </Button>
            )}
          </div>
        </Card>

        <Card title="Latest Parsed Invoice" subtitle="Extracted data from invoice pipeline">
          <div style={{ padding: '1rem', color: 'var(--muted)' }}>
            {!latestInvoiceResult?.invoice ? (
              <p style={{ margin: 0 }}>No invoice parsed yet</p>
            ) : (
              <div style={{ display: 'grid', gap: '0.35rem' }}>
                <p style={{ margin: 0 }}><strong style={{ color: 'var(--text)' }}>Invoice ID:</strong> {latestInvoiceResult.invoice.invoice_id || '-'}</p>
                <p style={{ margin: 0 }}><strong style={{ color: 'var(--text)' }}>Party:</strong> {latestInvoiceResult.invoice.party || '-'}</p>
                <p style={{ margin: 0 }}><strong style={{ color: 'var(--text)' }}>Amount:</strong> ₹{Number(latestInvoiceResult.invoice.amount || 0).toFixed(2)}</p>
                <p style={{ margin: 0 }}><strong style={{ color: 'var(--text)' }}>Date:</strong> {latestInvoiceResult.invoice.date ? new Date(latestInvoiceResult.invoice.date).toLocaleDateString() : '-'}</p>
                {latestInvoiceResult.deadline?.due_date && (
                  <p style={{ margin: 0 }}>
                    <strong style={{ color: 'var(--text)' }}>Auto Deadline:</strong> {latestInvoiceResult.deadline.due_date}
                  </p>
                )}
                {latestInvoiceResult.linked_transaction && (
                  <p style={{ margin: 0 }}>
                    <strong style={{ color: 'var(--text)' }}>Linked Category:</strong>{' '}
                    {latestInvoiceResult.linked_transaction.category || 'Uncategorized'}
                    {latestInvoiceResult.linked_transaction.sub_category ? ` / ${latestInvoiceResult.linked_transaction.sub_category}` : ''}
                  </p>
                )}
              </div>
            )}
          </div>
        </Card>

        <Card title="Sync Status" subtitle="Automatic bookkeeping updates" style={{ gridColumn: '1 / -1' }}>
          <div style={{
            padding: '1.5rem',
            background: 'var(--card-glow-emerald)',
            borderRadius: '0.5rem',
            borderLeft: '3px solid var(--emerald)',
          }}>
            <p style={{ margin: 0, color: 'var(--text)', display: 'inline-flex', alignItems: 'center', gap: '0.45rem' }}>
              <CheckCircle2 size={16} color="var(--emerald)" />
              <span>All systems synced. Your bookkeeping is up to date.</span>
            </p>
            {latestStatementResult && (
              <p style={{ margin: '0.5rem 0 0 0', color: 'var(--text)' }}>
                Last statement parse: {latestStatementResult.count} transaction(s) extracted.
              </p>
            )}
            {!!summary?.recommendations?.length && (
              <div style={{ marginTop: '0.75rem' }}>
                <p style={{ margin: 0, fontWeight: 600, color: 'var(--text)' }}>Recommendations</p>
                <ul style={{ margin: '0.35rem 0 0 1.1rem', padding: 0, color: 'var(--text)' }}>
                  {summary.recommendations.slice(0, 3).map((item, idx) => (
                    <li key={idx} style={{ marginBottom: '0.2rem' }}>{item}</li>
                  ))}
                </ul>
              </div>
            )}
            {!!summary?.balance_summary?.insights?.length && (
              <div style={{ marginTop: '0.75rem' }}>
                <p style={{ margin: 0, fontWeight: 600, color: 'var(--text)' }}>Insights</p>
                <ul style={{ margin: '0.35rem 0 0 1.1rem', padding: 0, color: 'var(--text)' }}>
                  {summary.balance_summary.insights.slice(0, 3).map((item, idx) => (
                    <li key={idx} style={{ marginBottom: '0.2rem' }}>{item}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </Card>
      </div>
    </PageShell>
  );
}
